<a href="https://colab.research.google.com/github/joshi-nitant/083_Nitant_Joshi/blob/master/Lab5/083_2_linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [3]:
# Imports
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [4]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 69.,  96.,  70.],
         [102.,  43.,  37.],
         [ 91.,  88.,  64.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.]]), tensor([[103., 119.],
         [ 22.,  37.],
         [ 81., 101.],
         [103., 119.],
         [ 56.,  70.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [ ]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[0.0748, 0.0456, 0.1499],
        [0.0955, 0.3244, 0.3621]], requires_grad=True)
---------
Parameter containing:
tensor([-0.4183,  0.5695], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [ ]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [5]:
# Import nn.functional
import torch.nn.functional as F

In [ ]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(3092.8308, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [ ]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [ ]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(16.1018, grad_fn=<MseLossBackward>)


In [ ]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.3027,  71.3401],
        [ 81.4444,  98.9748],
        [118.3745, 134.7551],
        [ 28.1233,  42.5342],
        [ 96.4180, 113.1091],
        [ 58.3027,  71.3401],
        [ 81.4444,  98.9748],
        [118.3745, 134.7551],
        [ 28.1233,  42.5342],
        [ 96.4180, 113.1091],
        [ 58.3027,  71.3401],
        [ 81.4444,  98.9748],
        [118.3745, 134.7551],
        [ 28.1233,  42.5342],
        [ 96.4180, 113.1091]], grad_fn=<AddmmBackward>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [ ]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(4.6856, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [6]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [8]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.33284602 0.09782918 0.54312336]
 [0.75947912 0.21899408 0.03359283]]
Biases:
[[0.61718326 0.05411424]
 [0.93805838 0.31266655]
 [0.21067148 0.13747607]
 [0.96870283 0.45291689]
 [0.86203438 0.25874352]
 [0.33898046 0.8603263 ]
 [0.74041129 0.80144882]
 [0.01654413 0.28993513]
 [0.74620454 0.3827298 ]
 [0.43893621 0.13978339]
 [0.28745513 0.86747773]
 [0.41940146 0.26487059]
 [0.96459971 0.12153731]
 [0.38767527 0.10055594]
 [0.21884889 0.80122269]]


In [9]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [10]:

# Generate predictions
preds = model(inputs)

In [11]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[54.82380248 71.6131849 ]
 [74.5959094  90.8466864 ]
 [73.77854067 97.50575029]
 [59.221216   88.57946707]
 [71.23864665 76.03773237]
 [54.54559968 72.41939697]
 [74.39826231 91.33546868]
 [73.58441332 97.65820935]
 [58.99871771 88.50927997]
 [70.81554848 75.91877225]
 [54.49407434 72.42654839]
 [74.07725248 90.79889045]
 [74.53246891 97.48981153]
 [58.64018844 88.22710612]
 [70.59546116 76.58021155]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [12]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [13]:
# Compute loss
loss = mse(preds, targets)
print(loss)

2062.5676912687445


In [14]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[-1228.00081057 -3282.3363762  -1590.94191663]
 [ -618.14397562 -2954.15926539 -1479.23934105]]
biases_grad:
[[-0.15682634  0.21509132]
 [-0.85387875 -1.35377515]
 [-6.02952791 -4.73256663]
 [ 4.9628288   6.87726228]
 [-4.23484711 -5.72830235]
 [-0.19392004  0.32258626]
 [-0.88023169 -1.28860418]
 [-6.05541156 -4.71223875]
 [ 4.93316236  6.867904  ]
 [-4.2912602  -5.7441637 ]
 [-0.20079009  0.32353979]
 [-0.923033   -1.36014794]
 [-5.92900415 -4.7346918 ]
 [ 4.88535846  6.83028082]
 [-4.32060518 -5.65597179]]


Adjust weights

In [15]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [16]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.34512603 0.13065255 0.55903278]
 [0.76566056 0.24853567 0.04838522]]
Biases:
[[0.61718483 0.05411209]
 [0.93806692 0.31268008]
 [0.21073177 0.1375234 ]
 [0.9686532  0.45284812]
 [0.86207673 0.2588008 ]
 [0.3389824  0.86032308]
 [0.74042009 0.80146171]
 [0.01660468 0.28998226]
 [0.74615521 0.38266112]
 [0.43897912 0.13984084]
 [0.28745713 0.86747449]
 [0.41941069 0.26488419]
 [0.964659   0.12158466]
 [0.38762642 0.10048764]
 [0.2188921  0.80127925]]


In [17]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1840.7587142143338


In [20]:
# repeating same for 200 times
for i in range(1111):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [21]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1.67467478338173


In [22]:
# Print predictions
print(preds)

[[ 57.30855878  70.1038881 ]
 [ 82.48710981 100.03062824]
 [118.53389349 133.85029746]
 [ 21.35636608  37.33623199]
 [102.23896454 117.94808424]
 [ 57.03084222  70.90869106]
 [ 82.28980816 100.51855622]
 [118.34010544 134.00249005]
 [ 21.13425667  37.26616756]
 [101.81660586 117.82933204]
 [ 56.97940694  70.91582998]
 [ 81.9693594   99.98291582]
 [119.28650401 133.83438656]
 [ 20.77635404  36.98448689]
 [101.59690322 118.48961527]]


In [23]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
